### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by nrdxp** [divnix/digga#121]
**Is your feature request related to a problem? Please describe.**
Obviously, if we are providing a template, we want to give users a solid idea of where they stand, and a clear upgrade path. Of course, this isn't urgent as flakes and the nix-command still haven't reached a stable release, but by the time they do, I'd like to have reached 1.0.0 (or close).

There are several usability improvements I'd like to see, so no need to rush. I went ahead and tagged 0.7.0.

### Third draft goals for 1.0:
- [x] A stable api and optimized structure #137
- [x] Refactor _and_ reduce lib
- [x] stop pushing directly to core (my fault)
- [ ] modules api, convertable to os, devshell, nm etc ([in Dhall?](https://dhall-lang.org)). #127 #38
- [x] generalize hosts
  - [x] Add Nixos [integration tests](https://www.haskellforall.com/2020/11/how-to-use-nixos-for-lightweight.html)
  - [x] The current, base override model is incredibly useful, but shouldn't be the only option. Generalize hosts/default.nix to allow for hosts with different versions. #117 
- [ ] generate lib documentation from the comments — shouldn't be terribly difficult to genaralize this [example](https://github.com/nix-community/rnix-parser/blob/master/examples/list-fns.rs)
- [x] Something solid for #106
- [ ] The remaining docmentation work finished #111
- [ ] make `defaultTemplate` a derivation that builds the mdbook for local reference and removes the source doc files
- [x] A solution for #118 — linked PR #135
- [ ] One line boostrap, even without nix — [nix-user-chroot](https://github.com/nix-community/nix-user-chroot#whishlist) already has that goal, so maybe we could help there.
- [x] Some tolerable solution to secrets #37, #56
- [x] Solve #91 — upgrading without the git history would be fantastic.
- [ ] Definitely need to implement #98 — this will probably wait until the stable release of nix-command.
- [ ] [Trustix](https://www.tweag.io/blog/2020-12-16-trustix-announcement) — when it's ready.

**Comment by tgunnoe** [comment]
I was just about to suggest the same thing.  

I cannot follow daily changes, when I'm changing my own, and at the same time figuring out how to upstream the useful parts to the template. I didn't even realize there was a new name for this project.

One suggestion would be to not try to abstract flakes so much.  I havent used the shell with `flk` related commands, because `nixos-rebuild switch/test/boot --flake '.#hostname'` is more direct relationship of understanding on a NixOS system. 

> '"If you try to hide the complexity of the system, you'll end up with a more complex system". Layers of abstraction that serve to hide internals are never a good thing. Instead, the internals should be designed in a way such that they NEED no hiding.'

... I think flakes and `nixos-rebuild` fit that description pretty well. 

there's so many great ideas in this template and its been very helpful. I hope to be caught up with the updates and contribute back soon!

**Comment by nrdxp** [comment]
Totally agree, flk is there mostly as a band-aid I always hoped to peel off as the ui moved toward stability.

Thanks for the insightful quote 👍

**Comment by codygman** [comment]
> I cannot follow daily changes, when I'm changing my own, and at the same time figuring out how to upstream the useful parts to the template.

Yeah, a few hours ago I tried to resolve conflicts between my branch that diverged at e67cd3701aa2a2081d0c261ccc12b47f743c0866 with master (currently 2cb1ec608196ebe8549ce10e53c563c0ebfbb38d) and I had to put it down for the weekend.

**Comment by Pacman99** [comment]
I think it will generally be easier once the api is stabilized and the format of the repo changes less often. And switching to suites will probably help.

**Comment by nrdxp** [comment]
For anyone subscribed to this, I have went ahead and tagged 0.7.0 so you can have a stable upgrade target. I'll probably release a few 0.7.x release shortly containing a lock file update and some doc fixes.

**Comment by Pacman99** [comment]
Closing this as most of it is done or no longer applicable. Anything important can get its own issue.
